version = 1

[disable_existing_loggers]
disable_existing_loggers = true

[formatters.simple]
format = '%(asctime)s %(levelname)-8s %(name)-10s: %(message)s'

[handlers.console]
class = 'logging.StreamHandler'
level = 'DEBUG'
formatter = 'simple'

[loggers.my_logger]
level = 'DEBUG'
handlers = ["console"]
propagate = false

[logging.root]
level = "INFO"
handlers = ["console"]